import cv2
import time
import filetype
import os
import argparse

## autogenerated code
## argument parser template
## update parser description and arguments

parser = argparse.ArgumentParser(description="py-sketch-image by jazlopez @ github.com", formatter_class=argparse.RawTextHelpFormatter)
parser.add_argument("--source", required=True, help="Path to image source")
args = parser.parse_args()

source = args.source
prefix = "sketch"

real_path = os.path.realpath(source)

if not os.path.exists(real_path):
    raise RuntimeError(f"Source file does not exist: {real_path}")

if not filetype.is_image(real_path):
    raise RuntimeError(f"{real_path} is not a valid image type. It could be damaged, corrupted or file is empty.")

base_name = os.path.basename(real_path)
directory = os.path.dirname(real_path)
sketch_filename = "{}_{}".format(prefix, base_name)
sketch_path = os.path.join(directory, sketch_filename)

print(f"sketch version of your image will be written to: {sketch_path}")
print("please wait.....")
time.sleep(1)
try:
    sk_gray, sk_color=cv2.pencilSketch(cv2.imread(source),
            sigma_s=10,
            sigma_r=0.15,
            shade_factor=0.099)
    cv2.imwrite(sketch_path, sk_gray)
except BaseException as e:

    print(f"Unable to create a sketch version of source image: {real_path}.\nAn error has occurred: {str(e)}")
    exit(1)

print("sketch image process is completed now... good bye")
exit(0)
